### ISSUE TITLE
How to use in a python project?

### ISSUE THREAD

**Issue by soppan** [robertmuth/Cwerg#20]
is there a pip package?

**Comment by soupsgit** [comment]
mainly the backend is what im interested in!

**Comment by robertmuth** [comment]
I have not found time to set up a pip package. 
The project might also be a bit premature for that.

There is a getting started page here:
https://github.com/robertmuth/Cwerg/blob/master/Docs/getting_started.md

But it is a bit light on the python stuff. In a nutshell:

1) clone the repo
2) set  `export PYTHONPATH=` to the root of the repo
3) try some of the examples in `Examples/`

If you notice gaps, errors, etc  in the documentation let me know or better yet send a pull request,

**Comment by soupsgit** [comment]
Thank you, i might use C++/C instead

**Comment by robertmuth** [comment]
The "getting started doc" has moved to:

https://github.com/robertmuth/Cwerg/blob/master/getting_started.md
