### ISSUE TITLE
benchmarks against standard compilers

### ISSUE THREAD

**Issue by rishavs** [robertmuth/Cwerg#22]
Hi

Do we have existing benchmarks of cwerg vs standard compiler backends like gcc, clang etc where we can look at differences in compile time, binary size, memory usage and compute performance numbers?
We can probably take a c program as the frontend input.

Also, can I recommend adding a Discussion to the repo so that questions which are not exactly bugs can go there (I don't want to pollute the repo with such questions)

**Comment by robertmuth** [comment]
Hi Rishav, 

Cwerg is still in its infancy and no efforts have been made at benchmarking or optimizing compile times.
The main issue is currently the lack of a  a proper frontend so this is where all the effort goes.

There is a quick and dirty frontend  for a subset of C which I do not plan to extend.
Example C code that can be handled by that frontend can be found in  FrontEndC/TestData/*.c
You could use these if you care to run benchmarks yourself.

**Comment by rishavs** [comment]
Thanks Robert. One more question;

> * Shared libs/dynamic linking adds complexity and slows programs down (both because
  of slower code idioms and prevention of optimizations), not
  to mention the DLL hell problem. (see also: https://drewdevault.com/dynlib, 
  https://www.kix.in/2008/06/19/an-alternative-to-shared-libraries/)
  (Lack of shared lib support likely precludes Windows as a target platform.) 

Does that, and the fact that ELF is the only output format supported means that Windows is out of scope for Swerg?

**Comment by robertmuth** [comment]
Changing the output format to coff or whatever windows is using would not be that hard but I think windows requires dynamic linking even for syscalls which drags in too much complexity.
