### ISSUE TITLE
New to repo!

### ISSUE THREAD

**Issue by csm-18** [robertmuth/Cwerg#38]
I am a beginner, want to contribute to the project.

I was unable to understand the structure of the project.
Like, how to build it, which is the front-end and which is the back-end.

**Comment by robertmuth** [comment]
I'll try to write something up shortly. 
Until then please have a look at the makefiles. They usually run extensive test when you invoke make without an argument. The makefiles are recursive but but not in a crazy way. 


The frontend is pretty self contained inside the directory with the same name. It also has a makefile as described above. 

If you have more questions just keep posting them to this thread. This will inform the content of the proper document I promised above

**Comment by csm-18** [comment]
Ok, thank you!

**Comment by robertmuth** [comment]
The backend directory organization is partially documented here: 
https://github.com/robertmuth/Cwerg/tree/master/Docs

**Comment by csm-18** [comment]
I'm encountering a build error related to the python location. The scripts seem to be hardcoded to use /usr/bin/python, while I'm using **_pyenv_** to manage my python environments.
Is there any workaround for this?

**Comment by robertmuth** [comment]
if you look at say  Base/Makefile 

the invocation of python is prefixed with    $(PYPY)  e.g.

 $(PYPY) ./reg_stats_test.py > $@.out 2>&1

so if you set PYPY to your python interpreter it should work
except there are probably some Makefiles that miss the prefix.

**Comment by csm-18** [comment]
Ok, got it!

**Comment by robertmuth** [comment]
I change the way the python interpreter is found - hopefully the PYPY workaround is no longer necessary.

I also revised the getting_started.md document which is now located here:
https://github.com/robertmuth/Cwerg/blob/master/getting_started.md

**Comment by csm-18** [comment]
Now it is all clear.
Got the test setup up and running!
![image](https://github.com/user-attachments/assets/a229e791-003a-4759-9b06-0bdba93b31fe)

tq!
